### ISSUE TITLE
reate_table_in_mysql_with_contextmanager.py 

### ISSUE THREAD

**Issue by baoshengzhu** [lalor/python_for_linux_system_administration#2]
运行 reate_table_in_mysql_with_contextmanager.py  脚本报错，但实际传参是str类型，
提示如下：
Traceback (most recent call last):
  File "create_table_in_mysql_with_contextmanager.py", line 53, in <module>
    main()
  File "create_table_in_mysql_with_contextmanager.py", line 45, in main
    with get_conn(**conn_args) as conn:
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "create_table_in_mysql_with_contextmanager.py", line 12, in get_conn
    db=kwargs.get('db'))
  File "/root/.pyenv/versions/env2712/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/root/.pyenv/versions/env2712/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 3 must be string, not None

**Comment by baoshengzhu** [comment]
找到原因了，是前面定义的是  passwd=kwargs.get('passwd'), 但是后面传输的是“password”
